### ISSUE TITLE
ios单发消息好像有问题

### ISSUE THREAD

**Issue by InVinCiblezz** [hacklee/php-umeng-notification#4]
我根据你的test 
安卓测试OK
ios有问题
我拿原生的发送成功
想问问
```
  $ios->sendIOSUnicast(
                [
                    'device_tokens' => 'a831b38d7ad34a12ad48775xxxcbf837d2473952066e8cdf687f550315736f75e4d',
                    'alert' => '123'
                ]);
```
还有就是报错消息如何获取啊?
发送try catch那没返回

**Comment by hacklee** [comment]
`UmengNotifyApi` 的 `sendCast` 方法没有再把异常抛出了。你可以修改一下，看看是否有异常输出

**Comment by InVinCiblezz** [comment]
`Http code:400 details:{\"ret\":\"FAIL\",\"data\":{\"error_code\":\"5000\"}}`
错误是这个 
不知道哪里有问题 我看了错误码是token不对
但是我拿这个token在原生下是ok的

**Comment by hacklee** [comment]
5000 是 **device_token错误** ，你看看是不是 产品模式`production_mode`  的设置有关，或者你这个 `token` 没有加入到测试机，然后用的测试模式

**Comment by InVinCiblezz** [comment]
production_mode 设置为false后ok 
感谢

**Comment by hacklee** [comment]
好的，如果的 `token` 为测试机，那么用测试模式，就只有测试机才会接收到消息推送了。
