### ISSUE TITLE
custom消息

### ISSUE THREAD

**Issue by InVinCiblezz** [hacklee/php-umeng-notification#5]
`{"appkey":"xxxx","production_mode":"false","description":"bkjbkblkjbjbl","type":"customizedcast","payload":{"display_type":"message","body":{"custom":"kdlfamsdlkfasdfas"}},"policy":{"expire_time":"2017-04-17 18:40:03"},"alias":"253971","alias_type":"user_id"}`
安卓想让我直接发一条这种消息 可以直接在app显示
我看了一下似乎没有能直接发这种的方法
只有改写 Class AndroidCustomizedcast
想问问看有直接可使用的方法吗？
thx

**Comment by InVinCiblezz** [comment]
主要就是设置了display_type 是message 还有 custom存放消息内容

**Comment by InVinCiblezz** [comment]
我仔细看了方法 已经知道了 
抱歉我太不仔细看代码了

**Comment by hacklee** [comment]
类似下面这样发就是上面的格式
````
$api->setAlias('253971')
    ->setAliasType('user_id')
    ->sendAndroidCustomizedcast([
        'display_type' => 'message',
        'custom' => 'kdlfamsdlkfasdfas',
        'expire_time' => '2017-04-17 18:40:03'
    ]);
````
